# Generated by Django 6.0.5 on 2026-06-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('KNV', 'Kiểm nghiệm viên'), ('QC', 'Trưởng phòng QC'), ('ADMIN', 'Quản trị viên')], default='KNV', max_length=10, verbose_name='Chức vụ / Vai trò'),
        ),
    ]
