# Generated by Django 6.0.5 on 2026-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_password_temp',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mật khẩu tạm (để copy)'),
        ),
    ]
