# Generated by Django 6.0.5 on 2026-06-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_customuser_birth_date_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plain_password_temp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_password_changed',
            field=models.BooleanField(default=False, verbose_name='Đã đổi mật khẩu lần đầu'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
    ]
