# Generated by Django 6.0.5 on 2026-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plain_password_temp',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mật khẩu tạm (để copy)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_password_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
