# Generated by Django 6.0.5 on 2026-06-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_customuser_birth_date_customuser_plain_password_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plain_password_temp',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mật khẩu tạm'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Người dùng'), ('ADMIN', 'Quản trị viên')], default='USER', max_length=10, verbose_name='Chức vụ / Vai trò'),
        ),
    ]
