# Generated by Django 5.0.3 on 2026-06-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coreapp', '0007_alter_customuser_is_password_changed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plain_password_temp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_required',
            field=models.BooleanField(default=False, verbose_name='Yêu cầu đặt lại mật khẩu'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_password_changed',
            field=models.BooleanField(default=False, verbose_name='Đã đổi mật khẩu'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='coreapp_cus_email_5b52a4_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='coreapp_cus_role_0b3b27_idx'),
        ),
    ]
