# Generated by Django 5.0.3 on 2026-07-19 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Đăng nhập'), ('LOGIN_FAILED', 'Đăng nhập thất bại'), ('LOGOUT', 'Đăng xuất'), ('USER_CREATED', 'Tạo tài khoản'), ('USER_DELETED', 'Xóa tài khoản'), ('PASSWORD_RESET', 'Đặt lại mật khẩu'), ('PASSWORD_CHANGED', 'Đổi mật khẩu'), ('USER_LOCKED', 'Khóa tài khoản'), ('USER_UNLOCKED', 'Mở khóa tài khoản'), ('DOC_APPROVED', 'Duyệt tài liệu'), ('DOC_REJECTED', 'Từ chối tài liệu'), ('MEDICINE_DELETED', 'Xóa dược phẩm')], max_length=30, verbose_name='Hành động')),
                ('target_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Loại đối tượng')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='ID đối tượng')),
                ('target_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên đối tượng')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Chi tiết thay đổi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký hệ thống',
                'verbose_name_plural': 'Nhật ký hệ thống',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='coreapp_sys_timesta_400fda_idx'), models.Index(fields=['action'], name='coreapp_sys_action_0a9cbb_idx'), models.Index(fields=['actor'], name='coreapp_sys_actor_i_8a8490_idx')],
            },
        ),
    ]
