# Generated by Django 5.0.3 on 2026-07-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_systemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Đăng nhập'), ('LOGIN_FAILED', 'Đăng nhập thất bại'), ('LOGOUT', 'Đăng xuất'), ('USER_CREATED', 'Tạo tài khoản'), ('USER_DELETED', 'Xóa tài khoản'), ('PASSWORD_RESET', 'Đặt lại mật khẩu'), ('PASSWORD_CHANGED', 'Đổi mật khẩu'), ('USER_LOCKED', 'Khóa tài khoản'), ('USER_UNLOCKED', 'Mở khóa tài khoản'), ('DOC_APPROVED', 'Duyệt tài liệu'), ('DOC_REJECTED', 'Từ chối tài liệu'), ('DOC_SCANNED', 'Quét tài liệu'), ('COA_SAVED', 'Lưu phiếu COA'), ('MEDICINE_CREATED', 'Thêm dược phẩm'), ('MEDICINE_UPDATED', 'Cập nhật dược phẩm'), ('MEDICINE_DELETED', 'Xóa dược phẩm'), ('PROFILE_UPDATED', 'Cập nhật hồ sơ')], max_length=30, verbose_name='Hành động'),
        ),
    ]
