# Generated by Django 5.0.3 on 2026-06-11 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=255, verbose_name='Tên thương mại')),
                ('active_ingredient', models.CharField(max_length=255, verbose_name='Hoạt chất')),
                ('strength', models.CharField(max_length=100, verbose_name='Hàm lượng')),
                ('dosage_form', models.CharField(max_length=100, verbose_name='Dạng bào chế')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Nhà sản xuất')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Số lô')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Số đăng ký')),
                ('mfg_date', models.CharField(blank=True, max_length=50, verbose_name='Ngày sản xuất')),
                ('exp_date', models.CharField(max_length=50, verbose_name='Hạn sử dụng')),
                ('indications', models.TextField(blank=True, verbose_name='Chỉ định')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
            ],
            options={
                'verbose_name': 'Dược phẩm',
                'verbose_name_plural': 'Dược phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên tệp')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày quét')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('accuracy_score', models.FloatField(default=0.0, verbose_name='Độ chính xác')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('medicine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.medicineitem', verbose_name='Dược phẩm')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_docs', to=settings.AUTH_USER_MODEL, verbose_name='Người kiểm duyệt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người quét')),
            ],
            options={
                'verbose_name': 'Tài liệu đã quét',
                'verbose_name_plural': 'Tài liệu đã quét',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
