# Generated by Django 5.0.3 on 2026-07-02 18:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightUniformityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_number', models.IntegerField(verbose_name='Số viên')),
                ('weight', models.CharField(max_length=50, verbose_name='Trọng lượng')),
                ('timestamp', models.DateTimeField(verbose_name='Thời gian đo')),
                ('balance_type', models.CharField(max_length=100, verbose_name='Loại cân')),
                ('snr', models.CharField(max_length=100, verbose_name='Số SNR')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('scanned_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.scanneddocument', verbose_name='Tài liệu đã quét')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người quét')),
            ],
            options={
                'verbose_name': 'Bản ghi đo trọng lượng',
                'verbose_name_plural': 'Các bản ghi đo trọng lượng',
                'ordering': ['pill_number'],
            },
        ),
    ]
