# Generated by Django 5.0.3 on 2026-07-19 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_weightuniformityrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCOAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(verbose_name='Nội dung COA (HTML)')),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lưu')),
                ('scanned_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.scanneddocument', verbose_name='Tài liệu gốc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người lưu')),
            ],
            options={
                'verbose_name': 'Phiếu báo cáo đã lưu',
                'verbose_name_plural': 'Các phiếu báo cáo đã lưu',
                'ordering': ['-saved_at'],
            },
        ),
    ]
